remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-include-cache

title: Apprends à coder tes propres jeux vidéos
tagline: Apprends le gamedev facilement
description: Suis les étapes, pas à pas pour apprendre à créer tes propres jeux vidéos

relative_links:
  enabled: true
  collections: true

exclude:
  - README.md
