remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Apprends a coder tes propres jeux videos]
tagline: [apprends le gamedev facilement]
description: [suis les etapes, pas à pas pour apprends a creer tes propres jeux videos]

plugins:
 - jekyll-relative-links

relative_links:
 enabled: true
 collections: true
 exclude:
 - README.md
